### ISSUE TITLE
Can't use python-pdfkit and wkhtmltopdf on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by mirzadelic** [JazzCore/python-pdfkit#176]
I am having a problem using `python-pdfkit` and `wkhtmltopdf` with Ubuntu 16.04 LTS server.

Installed python-pdfkit with pip and wkhtmltopdf from this bash script https://github.com/JazzCore/python-pdfkit/blob/master/travis/before-script.sh 

Locally on mac setup I did it with brew and I get pdfs printed, but on Linux server, I am getting an error:
```

[2020-11-26 09:18:10,698] urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:847)'),)': /api/1895361/store/ (connectionpool 14509 140240592238336)
[2020-11-26 09:23:57,209] django.request ERROR    Internal Server Error: /pdf-doc (log 14986 140683311347584)
Traceback (most recent call last):
  File "/home/uptree/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/uptree/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/uptree/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/uptree/src/uptree/apps/common/mixins.py", line 30, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/uptree/src/uptree/apps/common/mixins.py", line 43, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/uptree/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/uptree/src/uptree/apps/courses/views.py", line 153, in get
    content = pdfkit.from_string(html, False, options)
  File "/home/uptree/venv/lib/python3.6/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/home/uptree/venv/lib/python3.6/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Error: Authentication Required
Error: Authentication Required
```

Can someone help me solve this, any suggestions?

**Comment by sscotti** [comment]
Not off hand, but you might check the permissions to make sure it is executable and that the user trying to run it has permissions:  e.g. 755.

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
